services:
  # Backend API Service
  - type: web
    name: movie-recommendation-api
    runtime: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: TMDB_API_KEY
        sync: false
      - key: TMDB_BASE_URL
        value: https://api.themoviedb.org/3
    healthCheckPath: /

  # Frontend Static Site
  - type: web
    name: movie-recommendation-frontend
    runtime: static
    region: oregon
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://movie-recommendation-api.onrender.com/api
      - key: REACT_APP_TMDB_IMAGE_BASE_URL
        value: https://image.tmdb.org/t/p/w500
    routes:
      - type: rewrite
        source: /*
        destination: /index.html